apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-matching-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-matching-api
  template:
    metadata:
      labels:
        app: job-matching-api
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: job-matching-api
        image: jobmatchingapi.azurecr.io/job-matching-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: database-url
        - name: JINA_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: jina-api-key
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: groq-api-key