apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-matching-api
  labels:
    app: job-matching-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-matching-api
  template:
    metadata:
      labels:
        app: job-matching-api
    spec:
      containers:
      - name: job-matching-api
        image: ${REGISTRY_NAME}.azurecr.io/job-matching-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: database-url
        - name: JINA_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: jina-api-key
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: groq-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: job-matching-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: job-matching-api